// app/pages/auth/signup/index.vue
<template>
    <NuxtLayout name="auth-form">
        <h1 class="text-4xl xs:text-5xl font-semibold">Welcome</h1>

        <span
            >Have an account?
            <ULink :to="withCallback('/auth/signin')">Sign in</ULink></span
        >

        <UForm
            :schema="schema"
            :state="state"
            class="flex flex-col gap-3"
            @submit="onSubmit"
        >
            <UFormField label="Email" name="email">
                <UInput
                    class="w-full"
                    placeholder="john@example.com"
                    v-model="state.email"
                    :spellcheck="false"
                />
            </UFormField>
            <UFormField
                label="Password"
                name="password"
                :ui="{ error: 'hidden' }"
            >
                <UPasswordInput
                    class="w-full"
                    placeholder="password"
                    v-model="state.password"
                    :checkStrength="true"
                />
            </UFormField>
            <UButton
                type="submit"
                color="neutral"
                trailing-icon="i-lucide-arrow-right"
                class="group"
                :loading="submitting"
                :disabled="submitting"
                :ui="{
                    trailingIcon:
                        'group-enabled:group-hover:translate-x-1 group-enabled:group-focus-visible:translate-x-1 transition-transform duration-300',
                }"
            >
                <span class="text-left w-full">Sign up</span>
            </UButton>
        </UForm>

        <span class="text-sm text-muted"
            >By creating an account, you agree to zipft's
            <ULink to="/legal/terms-of-service" target="_blank"
                >Terms of Service</ULink
            >
            and consent to zipft's
            <ULink to="/legal/privacy-policy" target="_blank"
                >Privacy Policy</ULink
            >.</span
        >
    </NuxtLayout>
</template>

<script setup lang="ts">
import * as y from "yup";
import { emailSchema, passwordSchema } from "~~/shared/schema/auth";
import type { FormSubmitEvent } from "@nuxt/ui";
import { FetchError } from "ofetch";
import type { H3Error } from "h3";
import useCallback from "~/composables/callback";

useHead({ title: "Sign up :: zipft" });

const { withCallback } = useCallback();

const toast = useToast();

const schema = y.object({
    email: emailSchema.required("Required"),
    password: passwordSchema.required("Required"),
});
type Schema = y.InferType<typeof schema>;

const route = useRoute();
const state = reactive<Schema>({
    email: (route.query.email as string) || "",
    password: "",
});

const submitting = ref<boolean>(false);
async function onSubmit(event: FormSubmitEvent<Schema>) {
    submitting.value = true;

    try {
        await $fetch("/api/v1/user", {
            method: "POST",
            body: event.data,
        });
        await navigateTo(withCallback(`/auth/verify/request?e=${state.email}`));
    } catch (e: any) {
        if (!(e instanceof FetchError)) {
            console.log(e);
            toast.add({
                title: "Unknown error",
                description: e?.data?.message || e?.message || "Unknown error",
                color: "error",
            });
            return;
        }

        const error = e.data as H3Error;
        toast.add({
            title: error.name,
            description: error.message,
            icon: "i-lucide-x",
            color: "error",
        });
    } finally {
        submitting.value = false;
    }
}
</script>

// src/routes/(auth)/signup/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { superForm } from 'sveltekit-superforms/client';
	import { signUpSchema } from '$lib/schemas/auth';
	import { zod } from 'sveltekit-superforms/adapters';

	import Spinner from '$lib/assets/icons/Spinner.svelte';
	import ChevronRight from '$lib/assets/icons/ChevronRight.svelte';

	export let data: PageData;

	const { form, errors, enhance, delayed } = superForm(data.form, {
		validators: zod(signUpSchema)
	});
</script>

<svelte:head>
	<title>Sign up :: zipft</title>
</svelte:head>

<div class="mt-20">
	<form method="POST" use:enhance class="xs:w-[360px] flex w-full flex-col gap-4 px-4 md:px-0">
		<div class="flex flex-col gap-1">
			<h1 class="text-4xl font-bold">Welcome</h1>
			<span class="text-primary-700 flex flex-row">
				<p>Have an account?&nbsp;</p>
				<a
					href="/signin"
					class="w-fit underline underline-offset-2 hover:no-underline focus-visible:no-underline"
					>Sign in</a
				>
			</span>
		</div>
		<div class="flex flex-col gap-2">
			<div class="flex flex-row gap-2">
				<div class="flex flex-col gap-2">
					<label for="first" class="flex flex-col">
						First Name
						<input
							name="first"
							type="text"
							placeholder="John"
							class="w-full"
							bind:value={$form.first}
						/>
					</label>
					{#if $errors.first}
						<small>{$errors.first}</small>
					{/if}
				</div>
				<div class="flex flex-col gap-2">
					<label for="last" class="flex flex-col">
						Last Name
						<input
							name="last"
							type="text"
							placeholder="Doe"
							class="w-full"
							bind:value={$form.last}
						/>
					</label>
					{#if $errors.last}
						<small>{$errors.last}</small>
					{/if}
				</div>
			</div>
			<label for="email" class="flex flex-col">
				Email
				<input
					name="email"
					type="email"
					placeholder="email@example.com"
					class="w-full"
					bind:value={$form.email}
				/>
			</label>
			{#if $errors.email}
				<small>{$errors.email}</small>
			{/if}
			<label for="password" class="flex flex-col">
				Password
				<input
					name="password"
					type="password"
					placeholder="Password"
					class="w-full"
					bind:value={$form.password}
				/>
			</label>
			{#if $errors.password}
				<small>{$errors.password}</small>
			{/if}
		</div>
		<button
			class="bg-primary-800 text-secondary enabled:hover:bg-accent focus-visible:bg-accent group flex flex-row items-center justify-between p-2.5 transition-all focus-visible:outline-1 focus-visible:outline-offset-1 focus-visible:outline-black disabled:opacity-50 md:text-lg"
			disabled={$delayed}
		>
			<p>Sign up</p>
			{#if $delayed}
				<Spinner class="h-5 w-5 animate-spin" />
			{:else}
				<ChevronRight
					class="h-3 w-3 -translate-x-1 group-hover:translate-x-0 group-focus-visible:translate-x-0"
				/>
			{/if}
		</button>
		<span class="text-primary-700">
			<p class="text-sm">
				By creating an account, you agree to zipft's&nbsp;<a
					href="/legal/terms-of-service"
					target="_blank"
					class="w-fit underline underline-offset-2 hover:no-underline focus-visible:no-underline"
					>Terms of Service</a
				>&nbsp;and consent to zipft's&nbsp;<a
					href="/legal/privacy-policy"
					target="_blank"
					class="w-fit underline underline-offset-2 hover:no-underline focus-visible:no-underline"
					>Privacy Policy</a
				>.
			</p>
		</span>
	</form>
</div>
